# GitLab CI/CD pipeline for Hugo deployment to GitLab Pages
image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  HUGO_ENV: production
  HUGO_ENABLEGITINFO: "true"

test:
  stage: test
  script:
    - hugo --gc --minify
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'

pages:
  stage: deploy
  environment:
    name: production
    url: https://hasanoj.gitlab.io/hasanoj
  script:
    - hugo --gc --minify
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
